### ISSUE TITLE
Not very applicable

### ISSUE THREAD

**Issue by angel482400** [rajeshmajumdar/BruteXSS#10]
Use python3 but can't use
problem:C:\Users\IsLab\Desktop\ingect\BruteXSS-master>py brutexss.py
  File "brutexss.py", line 490
    print 'Nothing happened'
                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Nothing happened')?

**Comment by omgnobody121** [comment]
use py2
