### ISSUE TITLE
License vs. screenshots???

### ISSUE THREAD

**Issue by kingthorin** [rajeshmajumdar/BruteXSS#6]
This screenshot doesn't make any sense given the license:
![brutexssstart 1](https://user-images.githubusercontent.com/7570458/56238081-93d4d480-605b-11e9-96b8-c4805bd0c997.png)

https://github.com/rajeshmajumdar/BruteXSS/blob/master/LICENSE
![image](https://user-images.githubusercontent.com/7570458/56238140-ba930b00-605b-11e9-8223-6743c53c11a5.png)

**Comment by rajeshmajumdar** [comment]
I ain’t a lawyer so no idea 😐😐
