### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by SCAMagic** [rajeshmajumdar/BruteXSS#8]
my machine has  already configured the python environment. when I click brutexss.py,nothing happened.I open cmd and cd it's directory，and then input brutexss.py,it reply 

  File "C:\Users\Administrator\Desktop\BruteXSS-master\brutexss.py", line 490
    print 'Nothing happened'
                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Nothing happened')?

what should I do to run it?help me,please!

**Comment by rajeshmajumdar** [comment]
Try running it with Python 2.x seems like you’re running it with Python 3.x

**Comment by SCAMagic** [comment]
> Try running it with Python 2.x seems like you’re running it with Python 3.x

I solved the problem perfectly with your suggestion.thank u very much!
